apiVersion: v1
kind: Service
metadata:
  name: {{ include "kanidm.fullname" . }}
  labels:
    {{- include "kanidm.labels" . | nindent 4 }}
  annotations:
    traefik.ingress.kubernetes.io/service.serversscheme: https # Set backend is HTTPS
    traefik.ingress.kubernetes.io/service.serverstransport: kube-system-https-transport@kubernetescrd
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.ports.https }}
      targetPort: https
      protocol: TCP
      name: https
    - port: {{ .Values.service.ports.ldaps }}
      targetPort: ldaps
      protocol: TCP
      name: ldaps
  selector:
    {{- include "kanidm.selectorLabels" . | nindent 4 }}
