apiVersion: v1
kind: Service
metadata:
  name: links
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "links.selectorLabels" . | nindent 4 }}