apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "homebridge.fullname" . }}
  labels:
    {{- include "homebridge.labels" . | nindent 4 }}
  {{- with .Values.pvc.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.pvc.storageClassName }}
  storageClassName: {{ .Values.pvc.storageClassName . }}
  {{- end }}
  accessModes:
    {{- include .Values.pvc.accessModes . | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.pvc.storage . }}
