apiVersion: v1
kind: Service
metadata:
  name: simple-link-shortener
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.ports.adminUI }}
      targetPort: http-admin
      protocol: TCP
      name: http-admin
    - port: {{ .Values.service.ports.forwarder }}
      targetPort: http-forwarder
      protocol: TCP
      name: http-forwarder
  selector:
    {{- include "simple-link-shortener.selectorLabels" . | nindent 4 }}
