apiVersion: v1
kind: Service
metadata:
  name: {{ include "lldap.fullname" . }}-ldap
  {{- with .Values.services.ldap.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  labels:
    {{- include "lldap.labels" . | nindent 4 }}
spec:
  type: {{ .Values.services.ldap.type }}
  ports:
    - port: {{ .Values.services.ldap.port }}
      targetPort: ldap
      protocol: TCP
      name: ldap
  {{- if .Values.dualStack.enabled }}
  ipFamilies:
    - IPv4
    - IPv6
  ipFamilyPolicy: PreferDualStack
  {{- end }}
  selector:
    {{- include "lldap.selectorLabels" . | nindent 4 }}