apiVersion: v1
kind: Service
metadata:
  name: {{ include "lldap.fullname" . }}
  labels:
    {{- include "lldap.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.ports.type }}
  ports:
    - port: {{ .Values.service.ports.ui.port }}
      targetPort: ui
      protocol: TCP
      name: ui
    - port: {{ .Values.service.ports.ldap.port }}
      targetPort: ldap
      protocol: TCP
      name: ldap
  selector:
    {{- include "lldap.selectorLabels" . | nindent 4 }}
