apiVersion: v1
kind: Service
metadata:
  name: {{ include "lldap.fullname" . }}-ui
  {{- with .Values.services.ui.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "lldap.labels" . | nindent 4 }}
spec:
  type: {{ .Values.services.ui.type }}
  ports:
    - port: {{ .Values.services.ui.port }}
      targetPort: ui
      protocol: TCP
      name: ui
  selector:
    {{- include "lldap.selectorLabels" . | nindent 4 }}