apiVersion: v1
kind: Service
metadata:
  name: oidc-forward-auth-middleware
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "oidc-forward-auth-middleware.selectorLabels" . | nindent 4 }}