apiVersion: v1
kind: Service
metadata:
  name: {{ include "vsftpd.fullname" . }}
  labels:
    {{- include "vsftpd.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.ports.containerPortControl }}
      nodePort: {{ .Values.service.ports.nodePortControl }}
      targetPort: ftpscontrol
      protocol: TCP
      name: ftpscontrol
    - port: {{ .Values.service.ports.containerPortData }}
      nodePort: {{ .Values.service.ports.nodePortData }}
      targetPort: ftpsdata
      protocol: TCP
      name: ftpsdata
  selector:
    {{- include "vsftpd.selectorLabels" . | nindent 4 }}
