apiVersion: v1
kind: Service
metadata:
  name: {{ include "kanidm.fullname" . }}
  labels:
    {{- include "kanidm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.ports.http }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.ports.ldaps }}
      targetPort: ldaps
      protocol: TCP
      name: ldaps
  selector:
    {{- include "kanidm.selectorLabels" . | nindent 4 }}
