# TODO: Update in case of http backend available.
# Nginx is required because kanidm offers a sself-signed https backend
# which is incompatible with the ingress controller.
#
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kanidm.fullname" . }}-nginx
data:
  default.conf: |+
    server {
        listen       8080;
        listen  [::]:8080;
        server_name  localhost;
        location / {
            proxy_pass https://127.0.0.1:8443;
            proxy_ssl_verify off;
            proxy_ssl_server_name on;
        }
    }
