replicaCount: 1

image:
  repository: nitnelave/lldap
  pullPolicy: IfNotPresent
  tag: "v0.5.0"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}

services:
  ui:
    type: ClusterIP
    port: 17170
    annotations: {}
  ldap:
    type: ClusterIP
    port: 3890
    annotations: {}
    # metallb.universe.tf/address-pool: default

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}

persistence:
  enabled: true
  annotations: {}
  accessMode: ReadWriteOnce
  size: 2Gi
  storageClass: ""

livenessProbe:
  httpGet:
    path: /
    port: ui
readinessProbe:
  httpGet:
    path: /
    port: ui

# Additional volumes on the output Deployment definition.
volumes: []

# Additional volumeMounts on the output Deployment definition.
volumeMounts: []

nodeSelector: {}

tolerations: []

affinity: {}

ldapBaseDN: "dc=example,dc=com" 

dualStack:
  enabled: false
