replicaCount: 1

image:
  repository: ghcr.io/espresso-lab/oidc-forward-auth-middleware
  pullPolicy: Always
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

dnsPolicy: ClusterFirst

podAnnotations: {}
podLabels: {}

podSecurityContext:
  {}

securityContext:
  {}

service:
  type: ClusterIP
  ports:
    http: 3000

resources:
  {}

# Additional volumes on the output Deployment definition.
volumes: []

# Additional volumeMounts on the output Deployment definition.
volumeMounts: []

nodeSelector: {}

tolerations: []

affinity: {}

namespace: espresso-lab
