replicaCount: 1

image:
  repository: ghcr.io/espresso-lab/oidc-forward-auth-middleware
  pullPolicy: Always # TODO: Change in prod
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  ports:
    http: 3000

resources: {}

config:
  sessionCookieName: x_forward_auth_session

oidcProvider:
  # - ingressHostname: exmaple.com
  #   issuerUrl: https://id.example.com/oauth/app1
  #   clientId: app1
  #   clientSecret: mysecretpassword
  #   scopes: ["email", "profile"]

envExtra:
  - name: TEST
    value: ABCD

volumes: []

volumeMounts: []

nodeSelector: {}

tolerations: []

affinity: {}
