{{- if .Values.addons.istio.enabled }}

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  source:
    chart: istio/base
    repoURL: https://istio-release.storage.googleapis.com/charts
    targetRevision: 1.16.1
    helm:
      releaseName: istio
  destination:
    server: "https://kubernetes.default.svc"
    namespace: istio-system

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istiod
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  source:
    chart: istio/istiod
    repoURL: https://istio-release.storage.googleapis.com/charts
    targetRevision: 1.16.1
    helm:
      releaseName: istiod
  destination:
    server: "https://kubernetes.default.svc"
    namespace: istio-system

{{- end }}
