{{- if .Values.addons.knativeServing.enabled }}

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: knative-serving
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  source:
    chart: knative-serving
    repoURL: https://charts.softonic.io
    targetRevision: 3.0.0
    helm:
      releaseName: knative-serving
  destination:
    server: "https://kubernetes.default.svc"
    namespace: knative-serving

{{- end }}
