apiVersion: v1
kind: Service
metadata:
  name: webdav-s3-adapter
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "webdav-s3-adapter.selectorLabels" . | nindent 4 }}